services:
  frontend:
    build:
      context: .\frontend\albumlog-front-main
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build:
      context: .\backend
    env_file:
      - .\backend\.env
    ports:
      - "4444:4444"
  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    ports:
      - "9090:9090"
    volumes:
      - .\prometheus\prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - .\prometheus\alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
    depends_on:
      - backend
      - node-exporter

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    env_file:
      - .\.env
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"

volumes:
  grafana_data:
